AWSTemplateFormatVersion: 2010-09-09

Description: File Contain CloudFormation Nested Stack & CF File S3 URL

Parameters:

  VpcCIDR:
    Default: 10.0.0.0/16
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cloudformation-vpc-test-bucket.s3.amazonaws.com/vpc.yml
      Parameters:
        VpcCIDR: !Ref VpcCIDR


  PublicSubnet1Stack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: https://cloudformation-vpc-test-bucket.s3.amazonaws.com/public_subnet.yml
      TimeoutInMinutes: 3
      Parameters:
        VPC: !GetAtt VPCStack.Outputs.VPC



  PrivateSubnetStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: https://cloudformation-vpc-test-bucket.s3.amazonaws.com/private_subnet.yml
      TimeoutInMinutes: 3
      Parameters:
        VPC: !GetAtt VPCStack.Outputs.VPC


  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: https://cloudformation-vpc-test-bucket.s3.amazonaws.com/security_group.yml
      TimeoutInMinutes: 3
      Parameters:
        VPC: !GetAtt VPCStack.Outputs.VPC
