apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: verisys-worker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: verisys-worker
  minReplicas: 2 # Adjust as needed
  maxReplicas: 4 # Adjust as needed
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80%
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80%