apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-server-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: github_repo_url
    path: MinIO
    targetRevision: github_branch
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: meraid
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: verisys-backend-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: github_repo_url
    path: verisys-backend
    targetRevision: github_branch
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: meraid
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: verisys-worker-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: github_repo_url
    path: verisys-worker
    targetRevision: github_branch
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: meraid
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: verisys-captcha-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: github_repo_url
    path: verisys-captcha-model
    targetRevision: github_branch
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: meraid
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: github_repo_url
    path: database/scylla
    targetRevision: github_branch
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: meraid
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-conf
  namespace: argocd
spec:
  project: default
  source:
    repoURL: github_repo_url
    path: Nginx_Config
    targetRevision: github_branch
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: meraid
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
