kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-pvc-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  volumeName: minio-pv
  storageClassName: local-storage